### ISSUE TITLE
ERROR in Neo4j Desktop via browser:  ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser ...

### ISSUE THREAD

**Issue by Maddocent** [ontox-hu/aspis4j#23]
When running Docker container from remote VM, in local browser, via VS Code.  

> ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3

possible solution: https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/

 - [ ] Tried putting ``` ## edit neo4j config to accept remote connections
RUN echo "dbms.connector.bolt.address=0.0.0.0:7687" > var/lib/neo4j/conf/neo4j.conf``` in Dockerfile -> needs fix on path: getting:  ---> Running in 4fe5a6eca3aa
/bin/sh: 1: cannot create var/lib/neo4j/conf/neo4j.conf: Directory nonexistent
The command '/bin/sh -c echo "dbms.connector.bolt.address=0.0.0.0:7687" > var/lib/neo4j/conf/neo4j.conf' returned a non-zero code: 2
ERROR: Service 'ontox4j' failed to build : Build failed
 - [ ] possible confounder: https://community.neo4j.com/t/cannot-edit-neo4j-conf/643/4

**Comment by tomlue** [comment]
@Maddocent I believe this issue is resolved. Can you confirm?
