### ISSUE TITLE
Unique compounds in aspis4j? -> CTD data?

### ISSUE THREAD

**Issue by Maddocent** [ontox-hu/aspis4j#40]
When querying the aspis4j db for unique values of the 'ChemicalName' attribute for Chemical nodes. I get the list below. It seems to return only compounds starting with 'x' or a 'y' in the name. Is the full CTD db in the database, or only a specific subset? Or am I missing something here?

cypher query:
```
MATCH (c:Chemical) RETURN DISTINCT c.ChemicalName
```

"c.ChemicalName"                                                      │
╞══════════════════════════════════════════════════════════════════════╡
│"X-206, polyether antibiotic"                                         │
├──────────────────────────────────────────────────────────────────────┤
│"X22 compound"                                                        │
├──────────────────────────────────────────────────────────────────────┤
│"X 2616"                                                              │
├──────────────────────────────────────────────────────────────────────┤
│"X 33 compound"                                                       │
├──────────────────────────────────────────────────────────────────────┤
│"X-370 compound"                                                      │
├──────────────────────────────────────────────────────────────────────┤
│"X-387"                                                               │
├──────────────────────────────────────────────────────────────────────┤
│"X-3 xanthone compound"                                               │
├──────────────────────────────────────────────────────────────────────┤
│"X480"                                                                │
├──────────────────────────────────────────────────────────────────────┤
│"X 50"                                                                │
├──────────────────────────────────────────────────────────────────────┤
│"X607 fiber"                                                          │
├──────────────────────────────────────────────────────────────────────┤
│"X66 compound"                                                        │
├──────────────────────────────────────────────────────────────────────┤
│"X 6882"                                                              │
├──────────────────────────────────────────────────────────────────────┤
│"X6G azo-dye light yellow"                                            │
├──────────────────────────────────────────────────────────────────────┤
│"X 910279"                                                            │
├──────────────────────────────────────────────────────────────────────┤
│"X 9121"                                                              │
├──────────────────────────────────────────────────────────────────────┤
│"X 941204"                                                            │
├──────────────────────────────────────────────────────────────────────┤
│"X 941224"                                                            │
├──────────────────────────────────────────────────────────────────────┤
│"XA043 antibiotic"                                                    │
├──────────────────────────────────────────────────────────────────────┤
│"XAD-1600"                                                            │
├──────────────────────────────────────────────────────────────────────┤
│"XAD-4 resin"                                                         │
├──────────────────────────────────────────────────────────────────────┤
│"XAGE1A protein, human"                                               │
├──────────────────────────────────────────────────────────────────────┤
│"Xai-K protein"                                                       │
├──────────────────────────────────────────────────────────────────────┤
│"Xalacom"                                                             │
├──────────────────────────────────────────────────────────────────────┤
│"xaliproden"                                                          │
├──────────────────────────────────────────────────────────────────────┤
│"XAMA 7"                                                              │
├──────────────────────────────────────────────────────────────────────┤
│"Xamoterol"                                                           │
├──────────────────────────────────────────────────────────────────────┤
│"XAMR 0721"                                                           │
├──────────────────────────────────────────────────────────────────────┤
│"xanafide"                                                            │
├──────────────────────────────────────────────────────────────────────┤
│"xanalteric acid I"                                                   │
├──────────────────────────────────────────────────────────────────────┤
│"Xancor"                                                              │
├──────────────────────────────────────────────────────────────────────┤
│"xanifolia O54"                                                       │
├──────────────────────────────────────────────────────────────────────┤
│"xanomeline"                                                          │
├──────────────────────────────────────────────────────────────────────┤
│"xanosporic acid"                                                     │
├──────────────────────────────────────────────────────────────────────┤
│"xanosporolactone"    

ETC...

**Comment by Maddocent** [comment]
Maybe I solved this by running this:

```
MATCH (c:Chemical)
WITH c.ChemicalName as chemName
ORDER BY chemName
WITH collect(chemName) AS chemNames		// <== usernames is now a list :p
RETURN size(chemNames) AS chemCount, chemNames[0..25] as chemNames
```
I got 2001 as chemCount

The first 25 chemNames are:

═══════════╤══════════════════════════════════════════════════════════════════════╕
│"chemCount"│"chemNames"                                                           │
╞═══════════╪══════════════════════════════════════════════════════════════════════╡
│2001       │["((Z)-1-thiophen-2-ylethylideneamino)thiourea","(YEE(ah-GalNAc)3)-SMC│
│           │C-AET-pU(m)pT(7)","(Z)-(+,-)-2-(N-benzylindol-3-ylmethylene)quinuclidi│
│           │n-3-ol","(Z)-1-((naphthalen-2-ylamino)methylene)naphthalen-2(1H)-one",│
│           │"(Z)-1-(2-oxo-3-(1H-pyrrol-2-ylmethylene)-2,3-dihydro-1H-indol-6-yl)-3│
│           │-phenyl-urea","(Z)-1-(3-hydroxy-2,4-dimethoxy-phenyl)-3-(4-hydroxy-3-m│
│           │ethoxy-phenyl)propene","(Z)-10-hydroxy-7-isopropyl-5,10-dimethylcyclod│
│           │ec-4-ene-3,6-dione","(Z)-14-hydroxy-12,13-methano-8-nonadecenoic acid"│
│           │,"(Z)-2,3-bis(4-chlorophenylselanyl)prop-2-en-1-ol","(Z)-2,3-diphenyla│
│           │crylonitrile","(Z)-2-((1H-indazol-3-yl)methylene)-6-((11)C)methoxy-7-(│
│           │piperazin-1-ylmethyl)benzofuran-3(2H)-one","(Z)-2-(1-benzyl-5-nitro-1H│
│           │-indol-3-ylmethylene)-1-azabicyclo(2.2.2)octan-3-one","(Z)-2-(1H-indol│
│           │-3-ylmethylene)-1-azabicyclo(2.2.2)octan-3-one","(Z)-2-(2-chloroacetam│
│           │ido-4-thiazolyl)-2-(methoxyimino)acetic acid","(Z)-2-(3-Chlorobenzylid│
│           │ene)-3,4-dihydro-N-(2-methoxyethyl)-3-oxo-2H-benzo(b)(1,4)oxazine-6-ca│
│           │rboxamide","(Z)-2-(3-ethenyl-4-methyl-5-oxo-1,5-dihydro-2H-pyrrol-2-yl│
│           │idene)ethanamide","(Z)-2-(3-methoxybenzylidene)-1-azabicyclo(2.2.2)oct│
│           │an-3-one","(Z)-2-(4'-methoxy-3'-aminophenyl)-1-(3,4,5-trifluorophenyl)│
│           │ethene","(Z)-2-(4-ethylbenzylidene)-4,6-dimethoxy-2,3-dihydro-1H-indol│
│           │-3-one","(Z)-2-(6-(thieanisyl-2-yl)hexa-3-en-1,5-diynyl)benzenamine","│
│           │(Z)-2-(9-anthrylmethoxy)-1-phenyldiazene 1-oxide","(Z)-2-(N-benzylindo│
│           │l-3-ylmethylene)quinuclidin-3-one","(Z)-2-acetoxy-3-(3,4-dihydroxyphen│
│           │yl)acrylic acid","(Z)-2-amino-1,5-dihydro-1-methyl-5-(4-(mesyl)benzyli│
│           │dene)-4H-imidazol-4-one mesilate","(Z)-2-amino-5-chlorobenzophenonamid│
│           │inohydrazone acetate"]                                                │
└───────────┴──────────────────────────────────────────────────────────────────────┘

**Comment by tomlue** [comment]
moving to biobricks-okg. BB-okg can help with this and other issues. Contact me if interested.
